config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root "home#index", as: "home"
  get "/questions/list", to: "home#show", as: "questions"
  resources :test_questions
  resources :classic_questions
  get "/users/list", to: "user#show"
  get '/users/update/:id', to: 'user#update', as: 'user_update'
  get "/lessons/list", to: "lessons#show"
  resources :lessons
  resources :prepare_exams
  post 'prepare_exams', to: "prepare_exams#create"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def show
    @test_questions = TestQuestion.where(user_id: current_user.id)
    @classic_questions = ClassicQuestion.where(user_id: current_user.id)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.erb
<table style="float:left">
  <tr>
    <td>Soru</td>
    <td>Doğru Cevap</td>
    <td>Yanlış Cevap</td>
    <td>Yanlış Cevap</td>
    <td>Yanlış Cevap</td>
    <td>Yanlış Cevap</td>
    <td>Zorluk</td>
    <td>Tür</td>
    <td>Ders</td>
    <td>Resim</td>
    <td>Aksiyonlar</td>
  </tr>
  <% @test_questions.each do |question| %>
    <tr>
      <td><%= question.question %></td>
      <td><%= question.true_answer %></td>
      <td><%= question.wrong %></td>
      <td><%= question.wrong2 %></td>
      <td><%= question.wrong3 %></td>
      <td><%= question.wrong4 %></td>
      <td><%= question.difficulty %></td>
      <td><%= question.kind %></td>
      <td><%= question.lesson.name %></td>
      <td><%= image_tag(question.image, width: 200, height: 100) if question.image.attached? %></td>
      <td><%= link_to :Düzenle, edit_test_question_path(question) %> <%= link_to :Sil, test_question_path(question), method: :delete %></td>
    </tr>
  <% end %>
</table>
<table style="float:left">
  <tr>
    <td>Soru</td>
    <td>Doğru Cevap</td>
    <td>Zorluk</td>
    <td>Tür</td>
    <td>Ders</td>
    <td>Resim</td>
    <td>Aksiyonlar</td>
  </tr>
  <% @classic_questions.each do |question| %>
    <tr>
      <td><%= question.question %></td>
      <td><%= question.true_answer %></td>
      <td><%= question.difficulty %></td>
      <td><%= question.kind %></td>
      <td><%= question.lesson.name %></td>
      <td><%= image_tag(question.image, width: 200, height: 100) if question.image.attached? %></td>
      <td><%= link_to :Düzenle, edit_classic_question_path(question) %> <%= link_to :Sil, classic_question_path(question), method: :delete %></td>
    </tr>
  <% end %>
</table>