config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root "home#index", as: "home"
  get "/questions/list", to: "home#show", as: "questions"
  resources :test_questions
  resources :classic_questions
  get "/users/list", to: "user#show"
  get '/users/update/:id', to: 'user#update', as: 'user_update'
  get "/lessons/list", to: "lessons#show"
  resources :lessons
  resources :prepare_exams
  post 'prepare_exams', to: "prepare_exams#create"

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :test_questions
  has_many :classic_questions
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson, only: [:update, :edit, :destroy]
  before_action :admin_mi!

  def show
    @lesson = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(strong_params)
    if @lesson.save!
      flash[:succes] = "Ders eklendi..."
      redirect_to new_lesson_path
    else
      flash[:succes] = "Ders eklenemedi..."
      render :new
    end
  end

  def edit
  end

  def update
    if @lesson.update(strong_params)
      flash[:succes] = "Ders Güncellendi..."
      redirect_to lessons_list_path
    else
      flash[:succes] = "Ders Güncellenemedi..."
      render :edit
    end
  end

  def destroy
    @lesson.delete
    redirect_to lessons_path
  end

  private
  def strong_params
    params.require("lesson").permit(:name)
  end

  def admin_mi!
    unless current_user.is_admin
        redirect_to(home_path)
        flash[:danger] = "Bu sayfaya Erişemezsin..."
    end
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<html>
  <head>
    <%= csrf_meta_tags %>

    <link href="/stylesheets/test.scss" media="all" rel="stylesheet" type="text/css" />
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <div class="tcontainer">
      <%= form_for(@lesson) do |f| %>
        <div class="row">
          <div class="col-25">
            <label >Ders Adı</label>
          </div>
          <div class="col-75">
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="row">
          <%= f.submit "Ekle", class:"button"%>
        </div>
      <% end %>
    </div>
  </body>
</htlm>

app/views/lessons/edit.html.erb
<%= render "form" %>

app/views/lessons/new.html.erb
<%= render "form" %>

app/views/lessons/show.html.erb
<table style="float:left">
  <tr>
    <td>Adı</td>
    <td>Aksiyonlar</td>
  </tr>
  <% @lesson.each do |lesson| %>
    <tr>
      <td><%= lesson.name %></td>
      <td><%= link_to :Düzenle, edit_lesson_path(lesson) %> <%= link_to :Sil, lesson_path(lesson), method: :delete %></td>
    </tr>
  <% end %>
</table>