config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root "home#index", as: "home"
  get "/questions/list", to: "home#show", as: "questions"
  resources :test_questions
  resources :classic_questions
  get "/users/list", to: "user#show"
  get '/users/update/:id', to: 'user#update', as: 'user_update'
  get "/lessons/list", to: "lessons#show"
  resources :lessons
  resources :prepare_exams
  post 'prepare_exams', to: "prepare_exams#create"

end

app/controllers/prepare_exams_controller.rb
class PrepareExamsController < ApplicationController
  def new

  end
  def create
    prepared_exam = PreparedExam.new(strong_params)
    prepared_exam.save!

    lesson_id = params['prepared_exam']['lesson_id']
    exam_type = params['prepared_exam']['difficulty'].to_i
    @test_sorulari = TestQuestion.where(kind: exam_type, lesson_id: lesson_id, difficulty: 0)
                          .order_by_rand
                          .limit(prepared_exam.test_kolay_soru_sayisi)
                          .all
    @test_sorulari += TestQuestion.where(kind: exam_type, lesson_id: lesson_id, difficulty: 1)
                          .order_by_rand
                          .limit(prepared_exam.test_orta_soru_sayisi)
                          .all
    @test_sorulari += TestQuestion.where(kind: exam_type, lesson_id: lesson_id, difficulty: 2)
                          .order_by_rand
                          .limit(prepared_exam.test_zor_soru_sayisi)
                          .all
    dizi = []
    @test_sorulari.each do |soru|
      dizi << soru.id
    end
    prepared_exam.test = dizi


    @classic_sorulari = ClassicQuestion.where(kind: exam_type, lesson_id: lesson_id, difficulty: 0)
                          .order_by_rand
                          .limit(prepared_exam.klasik_kolay_soru_sayisi)
                          .all
    @classic_sorulari += ClassicQuestion.where(kind: exam_type, lesson_id: lesson_id, difficulty: 1)
                          .order_by_rand
                          .limit(prepared_exam.klasik_orta_soru_sayisi)
                          .all
    @classic_sorulari += ClassicQuestion.where(kind: exam_type, lesson_id: lesson_id, difficulty: 2)
                          .order_by_rand
                          .limit(prepared_exam.klasik_zor_soru_sayisi)
                          .all
    dizi = []
    @classic_sorulari.each do |soru|
      dizi << soru.id
    end
    prepared_exam.classic = dizi
    prepared_exam.save!

    redirect_to prepare_exam_path(prepared_exam)
  end

  def show
    @exam = PreparedExam.find(params[:id])
    @sorular = []

    @exam.test.each do |e|
      @sorular << TestQuestion.find(e)
    end

    @exam.classic.each do |e|
      @sorular << ClassicQuestion.find(e)
    end
    
    render layout: false
  end
  private

  def strong_params
    params.require(:prepared_exam).permit(PreparedExam.column_names - ["created_at", "updated_at"])
  end
end

app/helpers/prepare_exams_helper.rb
module PrepareExamsHelper
end

app/views/prepare_exams/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="/stylesheets/test.scss" media="all" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <!--
    <form class="tcontainer" action="">
      <div class="row">
        <div class="col-25">
          <label>Ders</label>
        </div>
        <div class="col-75">
          <%= collection_select(:prepare_exam, :lesson_id, Lesson.all, :id, :name) %>
        </div>
        <div class="col-25">
          <label>Tür</label>
        </div>
        <div class="col-75">
          <select class="country" name="country">
            <option value="Vize">Vize</option>
            <option value="Final">Final</option>
            <option value="Büt">Büt</option>
          </select>
        </div>
        <div class="col-50">
          <div class="">
            <label>Test</label>
          </div>
          <div class="col-75">
            <div class="col-25">
              <label>Kolay</label>
            </div>
            <div class="col-25">
              <input type="number" class="form-control" name="kolay_test_soru_sayisi" placeholder="Soru Sayısı">
            </div>
          </div>
          <div class="col-75">
            <div class="col-25">
              <label>Orta</label>
            </div>
            <div class="col-25">
              <input type="text" id="lname" name="orta_test_soru_sayisi" placeholder="Soru Sayısı">
            </div>
          </div>
          <div class="col-75">
            <div class="col-25">
              <label>Zor</label>
            </div>
            <div class="col-25">
              <input type="text" id="lname" name="lastname" placeholder="Soru Sayısı">
            </div>
          </div>
        </div>
        <div class="col-50" >
          <div class="">
            <label>Klasik</label>
          </div>
          <div class="col-75">
            <div class="col-25">
              <label>Kolay</label>
            </div>
            <div class="col-25">
              <input type="text" id="lname" name="lastname" placeholder="Soru Sayısı">
            </div>
          </div>
          <div class="col-75">
            <div class="col-25">
              <label>Orta</label>
            </div>
            <div class="col-25">
              <input type="text" id="lname" name="lastname" placeholder="Soru Sayısı">
            </div>
          </div>
          <div class="col-75">
            <div class="col-25">
              <label>Zor</label>
            </div>
            <div class="col-25">
              <input type="text" id="lname" name="lastname" placeholder="Soru Sayısı">
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <input type="submit" name="gonder" value="Sınav Hazrılara" class="button">
      </div>
    </form>
    <div class="tcontainer">
    </div>
    --->
    <div class="tcontainer">

      <%= form_tag(prepare_exams_path, :method => "POST") do %>
        <h1>Klasik</h1>
        <div class="row">
          <%= label_tag(:q,"Kolay Soru Sayısı :", style: "float:left; width:50%") %>
          <%= number_field_tag(:'prepared_exam[klasik_kolay_soru_sayisi]', 0, style: "float:left; width:50%", class: "form-control", min: 0) %>
        </div>
        <div class="row">
          <%= label_tag(:q,"Orta Seviye Soru Sayısı :", style: "float:left; width:50%") %>
          <%= number_field_tag(:'prepared_exam[klasik_orta_soru_sayisi]', 0, style: "float:left; width:50%", class: "form-control", min: 0) %>
        </div>
        <div class="row">
          <%= label_tag(:q,"Zor Soru Sayısı :", style: "float:left; width:50%") %>
          <%= number_field_tag(:'prepared_exam[klasik_zor_soru_sayisi]', 0, style: "float:left; width:50%", class: "form-control", min: 0) %>
        </div>
        <h1>Test</h1>
        <div class="row">
          <%= label_tag(:q,"Kolay Soru Sayısı :", style: "float:left; width:50%") %>
          <%= number_field_tag(:'prepared_exam[test_kolay_soru_sayisi]', 0, style: "float:left; width:50%", class: "form-control", min: 0) %>
        </div>
        <div class="row">
          <%= label_tag(:q,"Orta Seviye Soru Sayısı :", style: "float:left; width:50%") %>
          <%= number_field_tag(:'prepared_exam[test_orta_soru_sayisi]', 0, style: "float:left; width:50%", class: "form-control", min: 0) %>
        </div>
        <div class="row">
          <%= label_tag(:q,"Zor Seviye Soru Sayısı :", style: "float:left; width:50%") %>
          <%= number_field_tag(:'prepared_exam[test_zor_soru_sayisi]', 0, style: "float:left; width:50%", class: "form-control", min: 0) %>
        </div>
        <div class="row">
          <%= collection_select(:prepared_exam, :lesson_id, Lesson.all, :id, :name) %>
        </div>
        <div class="row">
          <select class="country" name="prepared_exam[difficulty]">
            <option value="0">Vize</option>
            <option value="1">Final</option>
            <option value="2">Büt</option>
          </select>
        </div>
        <div class="row">
          <%= submit_tag("Hazırla") %>
        </div>

      <% end %>
    </div>

  </body>
</html>

app/views/prepare_exams/show.html.erb
<table>
  <tr>
    <td>Fırat Üniversitesi </td>
  </tr>


</table>