config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root "home#index", as: "home"
  get "/questions/list", to: "home#show", as: "questions"
  resources :test_questions
  resources :classic_questions
  get "/users/list", to: "user#show"
  get '/users/update/:id', to: 'user#update', as: 'user_update'
  get "/lessons/list", to: "lessons#show"
  resources :lessons
  resources :prepare_exams
  post 'prepare_exams', to: "prepare_exams#create"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sinavla</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Sinavla', home_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Anasayfa', home_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Test Sorusu Ekle', new_test_question_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Klasik Soru Ekle', new_classic_question_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Soru Düzenle', questions_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sınav Hazırla', new_prepare_exam_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Kullanıcı Düzenle', users_list_path, class: 'nav-link' if current_user.is_admin %>
          </li>
          <li class="nav-item">
            <%= link_to 'Ders Ekle', new_lesson_path, class: 'nav-link' if current_user.is_admin %>
          </li>
          <li class="nav-item">
            <%= link_to 'Ders Düzenle', lessons_list_path, class: 'nav-link' if current_user.is_admin %>
          </li>
          <li class="nav-item">
            <%= link_to "Çıkış Yap", destroy_user_session_path,method: :delete, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sinavla</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    

    <%= yield %>
  </body>
</html>